shared_snowflake_profile:
  target: prod
  outputs:
    dev:
      type: snowflake
      account: "{{ var('database_name', 'MONTANA-HHS') }}"
      user: "snowflake_execution_context"
      role: HHS_SFLK_PHSD_MIDIS_ANALYST_DEV
      warehouse: HHS_PHSD_MIDIS_DEV_ELT_WH
      database: "{{ var('database_name', 'HHS_WRKSPC_DB') }}"
      schema: public
      threads: 1
    
    prod:
      type: snowflake
      account: "{{ var('database_name', 'MONTANA-HHS') }}"
      user: "snowflake_execution_context"
      role: HHS_SFLK_PHSD_MIDIS_ANALYST_DEV
      warehouse: HHS_PHSD_MIDIS_DEV_ELT_WH
      database: "{{ var('database_name', 'HHS_WRKSPC_DB') }}"
      schema: "{{ var('schema_name', 'STAGING') }}"
      threads: 4
