# profiles.yml (commit this to GitHub)
shared_snowflake_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      # These will be automatically populated by Snowflake's execution context
      account: "{{ var('database_name', 'HHS_WRKSPC_DB') }}"
      # No user/password needed - Snowflake uses its own auth
      role: HHS_SFLK_PHSD_MIDIS_ANALYST_DEV
      warehouse: HHS_PHSD_MIDIS_DEV_ELT_WH
      database: "{{ var('database_name', 'HHS_WRKSPC_DB') }}"
      schema: "{{ var('staging_schema', 'STAGING') }}"
      threads: 1
